/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adminDashboardClasses;

/**
 *
 * @author CHANDAN
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLeftPanel = new javax.swing.JPanel();
        menuButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        topRightPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        profileBtn = new javax.swing.JButton();
        notificationBtn = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        flightsBtn = new javax.swing.JButton();
        bookingsBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        usersBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        dashboardCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        statcards = new javax.swing.JPanel();
        totalFlightsCard = new javax.swing.JPanel();
        activeBookingsCard = new javax.swing.JPanel();
        revenueCard = new javax.swing.JPanel();
        flightsCard = new javax.swing.JPanel();
        bookingsCard = new javax.swing.JPanel();
        reportsCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airline Admin Dashboard");
        setBackground(new java.awt.Color(11, 18, 32));

        mainPanel.setBackground(new java.awt.Color(11, 18, 32));
        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(7, 16, 26));
        topPanel.setPreferredSize(new java.awt.Dimension(70, 0));
        topPanel.setLayout(new java.awt.BorderLayout());

        topLeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        menuButton.setBackground(new java.awt.Color(11, 21, 32));
        menuButton.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        menuButton.setText("☰");
        topLeftPanel.add(menuButton);

        titleLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        titleLabel.setText("Airline Admin Panel");
        topLeftPanel.add(titleLabel);

        topPanel.add(topLeftPanel, java.awt.BorderLayout.CENTER);

        topRightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        searchField.setBackground(new java.awt.Color(11, 23, 36));
        searchField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        searchField.setText("Search . . .");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        topRightPanel.add(searchField);

        profileBtn.setText("Admin");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        topRightPanel.add(profileBtn);

        notificationBtn.setText("🔔");
        topRightPanel.add(notificationBtn);

        topPanel.add(topRightPanel, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(15, 23, 36));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        menuPanel.setPreferredSize(new java.awt.Dimension(100, 800));
        menuPanel.setLayout(new java.awt.GridLayout(8, 1, 0, 1));

        dashboardBtn.setBackground(new java.awt.Color(11, 21, 32));
        dashboardBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setBorder(null);
        menuPanel.add(dashboardBtn);

        flightsBtn.setBackground(new java.awt.Color(11, 21, 32));
        flightsBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        flightsBtn.setText("Flights");
        flightsBtn.setBorder(null);
        menuPanel.add(flightsBtn);

        bookingsBtn.setBackground(new java.awt.Color(11, 21, 32));
        bookingsBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        bookingsBtn.setText("Bookings");
        bookingsBtn.setBorder(null);
        menuPanel.add(bookingsBtn);

        reportsBtn.setBackground(new java.awt.Color(11, 21, 32));
        reportsBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        reportsBtn.setText("Reports");
        reportsBtn.setBorder(null);
        menuPanel.add(reportsBtn);

        usersBtn.setBackground(new java.awt.Color(11, 21, 32));
        usersBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        usersBtn.setText("Users");
        usersBtn.setBorder(null);
        menuPanel.add(usersBtn);

        settingsBtn.setBackground(new java.awt.Color(11, 21, 32));
        settingsBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        settingsBtn.setText("Settings");
        settingsBtn.setBorder(null);
        menuPanel.add(settingsBtn);

        refreshBtn.setBackground(new java.awt.Color(11, 21, 32));
        refreshBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        refreshBtn.setText("Refresh Data");
        refreshBtn.setBorder(null);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        menuPanel.add(refreshBtn);

        logoutBtn.setBackground(new java.awt.Color(11, 21, 32));
        logoutBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        menuPanel.add(logoutBtn);

        sidebarPanel.add(menuPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setBackground(new java.awt.Color(11, 18, 32));
        contentPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Welcome back, Admin");

        totalFlightsCard.setBackground(new java.awt.Color(11, 23, 34));
        totalFlightsCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout totalFlightsCardLayout = new javax.swing.GroupLayout(totalFlightsCard);
        totalFlightsCard.setLayout(totalFlightsCardLayout);
        totalFlightsCardLayout.setHorizontalGroup(
            totalFlightsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        totalFlightsCardLayout.setVerticalGroup(
            totalFlightsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        activeBookingsCard.setBackground(new java.awt.Color(11, 23, 34));
        activeBookingsCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout activeBookingsCardLayout = new javax.swing.GroupLayout(activeBookingsCard);
        activeBookingsCard.setLayout(activeBookingsCardLayout);
        activeBookingsCardLayout.setHorizontalGroup(
            activeBookingsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        activeBookingsCardLayout.setVerticalGroup(
            activeBookingsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        revenueCard.setBackground(new java.awt.Color(11, 23, 34));
        revenueCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout revenueCardLayout = new javax.swing.GroupLayout(revenueCard);
        revenueCard.setLayout(revenueCardLayout);
        revenueCardLayout.setHorizontalGroup(
            revenueCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        revenueCardLayout.setVerticalGroup(
            revenueCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statcardsLayout = new javax.swing.GroupLayout(statcards);
        statcards.setLayout(statcardsLayout);
        statcardsLayout.setHorizontalGroup(
            statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statcardsLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statcardsLayout.createSequentialGroup()
                            .addComponent(totalFlightsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(activeBookingsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(statcardsLayout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(revenueCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        statcardsLayout.setVerticalGroup(
            statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statcardsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statcardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statcardsLayout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(totalFlightsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(activeBookingsCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(revenueCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout dashboardCardLayout = new javax.swing.GroupLayout(dashboardCard);
        dashboardCard.setLayout(dashboardCardLayout);
        dashboardCardLayout.setHorizontalGroup(
            dashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(dashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardCardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(dashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardCardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(statcards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dashboardCardLayout.setVerticalGroup(
            dashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(dashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardCardLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel1)
                    .addContainerGap(281, Short.MAX_VALUE)))
            .addGroup(dashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardCardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(statcards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contentPanel.add(dashboardCard, "card2");

        javax.swing.GroupLayout flightsCardLayout = new javax.swing.GroupLayout(flightsCard);
        flightsCard.setLayout(flightsCardLayout);
        flightsCardLayout.setHorizontalGroup(
            flightsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        flightsCardLayout.setVerticalGroup(
            flightsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        contentPanel.add(flightsCard, "card3");

        javax.swing.GroupLayout bookingsCardLayout = new javax.swing.GroupLayout(bookingsCard);
        bookingsCard.setLayout(bookingsCardLayout);
        bookingsCardLayout.setHorizontalGroup(
            bookingsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        bookingsCardLayout.setVerticalGroup(
            bookingsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        contentPanel.add(bookingsCard, "card4");

        javax.swing.GroupLayout reportsCardLayout = new javax.swing.GroupLayout(reportsCard);
        reportsCard.setLayout(reportsCardLayout);
        reportsCardLayout.setHorizontalGroup(
            reportsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        reportsCardLayout.setVerticalGroup(
            reportsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        contentPanel.add(reportsCard, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1208, 1208, 1208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(684, 684, 684)
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activeBookingsCard;
    private javax.swing.JButton bookingsBtn;
    private javax.swing.JPanel bookingsCard;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JPanel dashboardCard;
    private javax.swing.JButton flightsBtn;
    private javax.swing.JPanel flightsCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton notificationBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JPanel reportsCard;
    private javax.swing.JPanel revenueCard;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel statcards;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topLeftPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel topRightPanel;
    private javax.swing.JPanel totalFlightsCard;
    private javax.swing.JButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
