/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airnexa;

import java.awt.CardLayout;

/**
 *
 * @author CHANDAN
 */
public class AdminDashBoard extends javax.swing.JFrame {
    private boolean sidebarVisible = true;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashBoard.class.getName());

    /**
     * Creates new form AdminDashBoard
     */
    public AdminDashBoard() {
        initComponents();
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        sidebar = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JToggleButton();
        FlightsButton = new javax.swing.JToggleButton();
        BookingsButton = new javax.swing.JToggleButton();
        UsersButton = new javax.swing.JToggleButton();
        ReportsButton = new javax.swing.JToggleButton();
        SettingsButton = new javax.swing.JToggleButton();
        topbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topbarleft = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        Burger = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        FlightsPanel = new javax.swing.JPanel();
        flighttable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        top = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BookingsPanel = new javax.swing.JPanel();
        UsersPanel = new javax.swing.JPanel();
        ReportsPanel = new javax.swing.JPanel();
        SettingsPanel = new javax.swing.JPanel();
        DashBoardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 18, 32));

        sidebar.setBackground(new java.awt.Color(15, 23, 36));
        sidebar.setFocusable(false);
        sidebar.setPreferredSize(new java.awt.Dimension(150, 0));
        sidebar.setVerifyInputWhenFocusTarget(false);
        sidebar.setLayout(new java.awt.GridLayout(6, 1, 0, 1));

        DashboardButton.setBackground(new java.awt.Color(11, 21, 32));
        DashboardButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        DashboardButton.setText("DASHBOARD");
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });
        sidebar.add(DashboardButton);

        FlightsButton.setBackground(new java.awt.Color(11, 21, 32));
        FlightsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        FlightsButton.setText("MANAGE FLIGHTS");
        FlightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightsButtonActionPerformed(evt);
            }
        });
        sidebar.add(FlightsButton);

        BookingsButton.setBackground(new java.awt.Color(11, 21, 32));
        BookingsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        BookingsButton.setText("MANAGE BOOKING");
        BookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingsButtonActionPerformed(evt);
            }
        });
        sidebar.add(BookingsButton);

        UsersButton.setBackground(new java.awt.Color(11, 21, 32));
        UsersButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        UsersButton.setText("USERS");
        UsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButtonActionPerformed(evt);
            }
        });
        sidebar.add(UsersButton);

        ReportsButton.setBackground(new java.awt.Color(11, 21, 32));
        ReportsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        ReportsButton.setText("REPORTS");
        ReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsButtonActionPerformed(evt);
            }
        });
        sidebar.add(ReportsButton);

        SettingsButton.setBackground(new java.awt.Color(11, 21, 32));
        SettingsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        SettingsButton.setText("SETTINGS");
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });
        sidebar.add(SettingsButton);

        topbar.setBackground(new java.awt.Color(7, 16, 26));
        topbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        topbar.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AirNexa Admin Panel");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        topbar.add(jLabel1, java.awt.BorderLayout.CENTER);

        topbarleft.setOpaque(false);
        topbarleft.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setBackground(new java.awt.Color(11, 21, 32));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setText("🔔");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        topbarleft.add(jButton1);

        jButton2.setBackground(new java.awt.Color(200, 21, 32));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        topbarleft.add(jButton2);

        topbar.add(topbarleft, java.awt.BorderLayout.LINE_END);

        menu.setBackground(new java.awt.Color(11, 18, 32));

        Burger.setBackground(new java.awt.Color(20, 21, 32));
        Burger.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        Burger.setText("=");
        Burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerActionPerformed(evt);
            }
        });
        menu.add(Burger);

        topbar.add(menu, java.awt.BorderLayout.LINE_START);

        MainPanel.setBackground(new java.awt.Color(11, 18, 32));
        MainPanel.setLayout(new java.awt.CardLayout());

        FlightsPanel.setBackground(new java.awt.Color(11, 18, 32));
        FlightsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FlightsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FlightsPanel.setLayout(new java.awt.BorderLayout());

        flighttable.setBackground(new java.awt.Color(11, 18, 32));
        flighttable.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        flighttable.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(11, 18, 32));

        jTable1.setBackground(new java.awt.Color(7, 16, 24));
        jTable1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(7, 16, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(30, 41, 55));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 150));
        jTable1.setSelectionBackground(new java.awt.Color(6, 182, 212));
        jTable1.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTable1);

        flighttable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        FlightsPanel.add(flighttable, java.awt.BorderLayout.CENTER);

        top.setBackground(new java.awt.Color(11, 18, 32));
        top.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        top.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(200, 200, 200));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Flights ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        top.add(jLabel3, java.awt.BorderLayout.CENTER);

        FlightsPanel.add(top, java.awt.BorderLayout.PAGE_START);

        MainPanel.add(FlightsPanel, "FlightBox");

        BookingsPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout BookingsPanelLayout = new javax.swing.GroupLayout(BookingsPanel);
        BookingsPanel.setLayout(BookingsPanelLayout);
        BookingsPanelLayout.setHorizontalGroup(
            BookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        BookingsPanelLayout.setVerticalGroup(
            BookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        MainPanel.add(BookingsPanel, "BookingBox");

        UsersPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout UsersPanelLayout = new javax.swing.GroupLayout(UsersPanel);
        UsersPanel.setLayout(UsersPanelLayout);
        UsersPanelLayout.setHorizontalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        UsersPanelLayout.setVerticalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        MainPanel.add(UsersPanel, "UsersBox");

        ReportsPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout ReportsPanelLayout = new javax.swing.GroupLayout(ReportsPanel);
        ReportsPanel.setLayout(ReportsPanelLayout);
        ReportsPanelLayout.setHorizontalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        ReportsPanelLayout.setVerticalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        MainPanel.add(ReportsPanel, "ReportsBox");

        SettingsPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        MainPanel.add(SettingsPanel, "SettingsBox");

        DashBoardPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout DashBoardPanelLayout = new javax.swing.GroupLayout(DashBoardPanel);
        DashBoardPanel.setLayout(DashBoardPanelLayout);
        DashBoardPanelLayout.setHorizontalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        DashBoardPanelLayout.setVerticalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        MainPanel.add(DashBoardPanel, "DashBoardBox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "FlightBox");
        System.out.println("Flights clicked");
    }//GEN-LAST:event_FlightsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "BookingBox");
    }//GEN-LAST:event_BookingsButtonActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "ReportsBox");
    }//GEN-LAST:event_ReportsButtonActionPerformed

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "DashBoardBox");

    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "SettingsBox");
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void UsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "UsersBox");
    }//GEN-LAST:event_UsersButtonActionPerformed

    private void BurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerActionPerformed
        // TODO add your handling code here:
                                              
    new Thread(() -> {
        try {
            if (sidebarVisible) {
                for (int i = 220; i >= 0; i -= 10) {
                    sidebar.setPreferredSize(new java.awt.Dimension(i, sidebar.getHeight()));
                    sidebar.revalidate();
                    Thread.sleep(10);
                }
                sidebarVisible = false;
            } else {
                for (int i = 0; i <= 220; i += 10) {
                    sidebar.setPreferredSize(new java.awt.Dimension(i, sidebar.getHeight()));
                    sidebar.revalidate();
                    Thread.sleep(10);
                }
                sidebarVisible = true;
            }
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
    }).start();


    }//GEN-LAST:event_BurgerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BookingsButton;
    private javax.swing.JPanel BookingsPanel;
    private javax.swing.JButton Burger;
    private javax.swing.JPanel DashBoardPanel;
    private javax.swing.JToggleButton DashboardButton;
    private javax.swing.JToggleButton FlightsButton;
    private javax.swing.JPanel FlightsPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JToggleButton ReportsButton;
    private javax.swing.JPanel ReportsPanel;
    private javax.swing.JToggleButton SettingsButton;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JToggleButton UsersButton;
    private javax.swing.JPanel UsersPanel;
    private javax.swing.JPanel flighttable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel top;
    private javax.swing.JPanel topbar;
    private javax.swing.JPanel topbarleft;
    // End of variables declaration//GEN-END:variables
}
