/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airnexa;

/**
 *
 * @author User
 */

import java.awt.Dimension;
import java.awt.Point;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
//import java.awt.Image;
//import java.awt.image.BufferedImage;
//import java.io.ByteArrayInputStream;
//import javax.imageio.ImageIO;

public class UserDashboard extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt, stmt2;
    PreparedStatement pst;
    ResultSet rs, rs2;
    String dept, arrv;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();    
        try{           
            sp1.setVisible(false);
            
            b4.setVisible(false);
            b3.setVisible(false);
            b2.setVisible(false);
                        
            con = airnexa.DatabaseConnection.getConnection();
            
            String sql = "select distinct depart_from from flight order by depart_from asc";
            stmt = this.con.createStatement();
            rs = stmt.executeQuery(sql);
            
            String sql1 = "select distinct arrive_at from flight order by arrive_at asc";
            stmt2 = this.con.createStatement();
            rs2 = stmt2.executeQuery(sql1);
            c1.addItem("Select");
            c2.addItem("Select");
            
            while(rs.next()){
                c1.addItem(rs.getString("depart_from"));               
            }                
            while(rs2.next()){
                 c2.addItem(rs2.getString("arrive_at"));
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }              
    }     
    
//    boolean isLeapYear(int y){
//        return (((y%4 == 0) && (y%100 != 0)) || (y%400 == 0));        
//    }
//
//    static int getDays(String str){        
//        return switch (str) {
//            case "1", "3", "5", "7", "8", "10", "12" -> 31;
//            case "2" -> 28;
//            default -> 30;
//        };        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        workingPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        jp5 = new javax.swing.JPanel();
        h1 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        h2 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JButton();
        sp1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AirNexa");
        titlePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 186, 38));

        jButton1.setText("UserName");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        titlePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 220, -1));

        b2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        b2.setText("<--");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        titlePanel.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 60, -1));

        mainPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1000, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 550));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, -1, -1));

        workingPanel.setBackground(new java.awt.Color(255, 255, 255));
        workingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        l1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 28)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 0));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Book A Flight");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        workingPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp5.setBackground(new java.awt.Color(255, 255, 255));

        h1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        h1.setForeground(new java.awt.Color(0, 0, 0));
        h1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h1.setText("From");

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        h2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        h2.setForeground(new java.awt.Color(0, 0, 0));
        h2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h2.setText("To");

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        b1.setText("Search");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Departure From", "Departure Time", "Arrival At", "Ariival Time", "Airline", "Available Seat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp1.setViewportView(t1);

        b3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        b3.setText("Book");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        b4.setText("Filter");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b4)
                            .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sp1)
                                .addGroup(jp5Layout.createSequentialGroup()
                                    .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(b1))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        workingPanel.add(jp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 900, 400));

        mainPanel.add(workingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        profile pr = new profile();
        //this.setVisible(false);
        pr.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
           
        if(c2.getSelectedItem().toString().equalsIgnoreCase("Select") && c1.getSelectedItem().toString().equalsIgnoreCase("Select")){
        } else {
            dept = c1.getSelectedItem().toString();
            arrv = c2.getSelectedItem().toString();              
            if(b1.isVisible()){
                l1.setText("Flight Details");
                
                
                sp1.setVisible(true);
                sp1.setPreferredSize(new Dimension(836,257));

                b4.setVisible(true);
                b3.setVisible(true);
                b2.setVisible(true);

                b1.setVisible(false);

                h1.setVisible(false);
                h2.setVisible(false);

                c1.setVisible(false);
                c2.setVisible(false);       
            }
            
                
            try{                               
                if (!dept.equals("Select") && arrv.equals("Select")) {
                    pst = con.prepareStatement("SELECT * FROM flight WHERE depart_from = ?");
                    pst.setString(1, dept);
                } else if (dept.equals("Select") && !arrv.equals("Select")) {
                    pst = con.prepareStatement("SELECT * FROM flight WHERE arrive_at = ?");
                    pst.setString(1, arrv);
                } else if (!dept.equals("Select") && !arrv.equals("Select")) {
                    pst = con.prepareStatement("SELECT * FROM flight WHERE depart_from = ? AND arrive_at = ?");
                    pst.setString(1, dept);
                    pst.setString(2, arrv);
                }
                
                rs = pst.executeQuery();
                
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new String[] {
                    "Departure From", "Departure Time", "Arrival At",
                    "Arrival Time", "Airline", "Available Seat"
                });
                
                
                while(rs.next()){
                    String f = rs.getString("depart_from");
                    String dt = rs.getString("departure_time");
                    String ar = rs.getString("arrive_at");
                    String at = rs.getString("arrival_time");
                    String air = rs.getString("airline");
                    String s = rs.getString("seat_availability");

                    Object row[] = { f, dt, ar, at, air, s };
                    model.addRow(row);
                }
                t1.setModel(model);

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(b4.getText().equalsIgnoreCase("Filter") && b4.isVisible()){
            l1.setText("Book A Flight");
            b1.setText("Search");
            
            h1.setVisible(true);
            h2.setVisible(true);
            
            c1.setVisible(true);
            c2.setVisible(true);
            
            sp1.setVisible(false);
            
            b4.setVisible(false);
            b3.setVisible(false);
            b2.setVisible(false);
            
            b1.setVisible(true);                                         
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
        int selectedRow = t1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a flight to book.");
        }
                
        String f = t1.getValueAt(selectedRow, 0).toString();
        String dt = t1.getValueAt(selectedRow, 1).toString();
        String a = t1.getValueAt(selectedRow, 2).toString();
        String at = t1.getValueAt(selectedRow, 3).toString();
        String air = t1.getValueAt(selectedRow, 4).toString();
        String s = t1.getValueAt(selectedRow, 5).toString();

        this.setVisible(false);
        SearchFlight ob = new SearchFlight(f, dt, a, at, air, s);
        ob.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jp5;
    private javax.swing.JLabel l1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JTable t1;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel workingPanel;
    // End of variables declaration//GEN-END:variables

}
