/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Payment_and_Receipt;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author User
 */
public class NetBankingPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetBankingPanel
     */
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private final Payment parentFrame;
    
    public NetBankingPanel(Payment parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        try{
            con = UserEnd.DatabaseConnection.getConnection();        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private NetBankingPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private double getAmountFromPaymentFrame() {
        try{
            String sql = "select * from booking where booking_id = ?";
            pst = this.con.prepareStatement(sql);
            pst.setString(1, parentFrame.b_id);            
            rs = pst.executeQuery();
            
            if(rs.next()){
                return Double.parseDouble(rs.getString("ticket_price"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        return 0.0; // Example hardcoded value
    }

    private String formatPrice(double p) {
        // This method is from your main Payment class. You can copy it here
        // or call it from the parent frame.
        NumberFormat f = NumberFormat.getCurrencyInstance(new Locale("en", "IN"));
        return f.format(p);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JButton();

        l1.setFont(new java.awt.Font("Times New Roman", 0, 34)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Enter Card Details");

        c1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bank", "State Bank of India", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra Bank", "Punjab National Bank", "Bank of Baroda", "Union Bank of India", "Canara Bank", "Yes Bank" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        b1.setText("Confirm to Payment");
        b1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        String selectedBank = (String) c1.getSelectedItem();
        if ("Select Bank".equals(selectedBank)) {
            JOptionPane.showMessageDialog(this, "Please select a bank to proceed.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return; // Stop the process if no bank is selected
        }

        double amount = getAmountFromPaymentFrame();

        if(amount > 0.0){
            // Show a confirmation dialog
            int response = JOptionPane.showConfirmDialog(
                this,
                "You are about to pay " + formatPrice(amount) + " through " + selectedBank + ". Do you want to continue?",
                "Confirm Payment",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if (response == JOptionPane.YES_OPTION) {
                // If the user confirms, proceed with the simulated transaction
                parentFrame.simulatePayment();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
