/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airnexa.Admin;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHANDAN
 */
public class AdminDashBoard extends javax.swing.JFrame {

    private boolean sidebarVisible = true;
    private Timer sidebarTimer;
    private boolean isEditMode = false;
    private int editingFlightId = -1;
    Connection con;
    Statement stmt;
    ResultSet rs;
    String uname;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashBoard.class.getName());

    //constractors
    public AdminDashBoard() {

        initComponents();
        initFlightDialog();

        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "DashBoardBox");

        sidebarVisible = true;
        loadFlightData();
        loadBookingsData();

    }

    private void initFlightDialog() {
        FlightDialog.setModal(true);
        FlightDialog.setResizable(false);
        FlightDialog.pack();
        FlightDialog.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        FlightDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        Add1 = new javax.swing.JTextField();
        Add2 = new javax.swing.JTextField();
        Add3 = new javax.swing.JTextField();
        Add4 = new javax.swing.JTextField();
        Add5 = new javax.swing.JTextField();
        Add6 = new javax.swing.JTextField();
        depert = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        Add_save = new javax.swing.JButton();
        Add_cnl = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JToggleButton();
        FlightsButton = new javax.swing.JToggleButton();
        BookingsButton = new javax.swing.JToggleButton();
        UsersButton = new javax.swing.JToggleButton();
        ReportsButton = new javax.swing.JToggleButton();
        SettingsButton = new javax.swing.JToggleButton();
        topbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topbarleft = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        Burger = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        FlightsPanel = new javax.swing.JPanel();
        flighttable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        top = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addflight = new javax.swing.JButton();
        editflight = new javax.swing.JButton();
        deleteflight = new javax.swing.JButton();
        BookingsPanel = new javax.swing.JPanel();
        book_top = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bookingtable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        UsersPanel = new javax.swing.JPanel();
        ReportsPanel = new javax.swing.JPanel();
        SettingsPanel = new javax.swing.JPanel();
        DashBoardPanel = new javax.swing.JPanel();

        FlightDialog.setBackground(new java.awt.Color(11, 23, 34));
        FlightDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FlightDialog.setModal(true);

        jPanel2.setBackground(new java.awt.Color(11, 18, 32));

        Add1.setBackground(new java.awt.Color(1, 18, 32));
        Add1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));

        Add2.setBackground(new java.awt.Color(1, 18, 32));
        Add2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });

        Add3.setBackground(new java.awt.Color(1, 18, 32));
        Add3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));

        Add4.setBackground(new java.awt.Color(1, 18, 32));
        Add4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));

        Add5.setBackground(new java.awt.Color(1, 18, 32));
        Add5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));

        Add6.setBackground(new java.awt.Color(1, 18, 32));
        Add6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));

        depert.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        depert.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.MINUTE));
        depert.setName(""); // NOI18N

        jSpinner2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.MINUTE));
        jSpinner2.setName(""); // NOI18N

        Add_save.setBackground(new java.awt.Color(14, 165, 164));
        Add_save.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Add_save.setText("SAVE");
        Add_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_saveActionPerformed(evt);
            }
        });

        Add_cnl.setBackground(new java.awt.Color(239, 68, 68));
        Add_cnl.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Add_cnl.setText("CANCEL");
        Add_cnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_cnlActionPerformed(evt);
            }
        });

        l1.setBackground(new java.awt.Color(11, 18, 32));
        l1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Flight Number :");

        l2.setBackground(new java.awt.Color(11, 18, 32));
        l2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Flight Name :");

        l3.setBackground(new java.awt.Color(11, 18, 32));
        l3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Source :");

        l4.setBackground(new java.awt.Color(11, 18, 32));
        l4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Destination :");

        l5.setBackground(new java.awt.Color(11, 18, 32));
        l5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("Departure Time :");

        l6.setBackground(new java.awt.Color(11, 18, 32));
        l6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setText("Arrival Time :");

        l7.setBackground(new java.awt.Color(11, 18, 32));
        l7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setText("Available Seats :");

        l8.setBackground(new java.awt.Color(11, 18, 32));
        l8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setText("Ticket Price :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Add_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Add_cnl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Add4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Add6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(depert, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Add3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(343, 343, 343))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Add5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l1)
                        .addComponent(l2))
                    .addComponent(Add2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4)
                    .addComponent(Add3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5)
                    .addComponent(depert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7)
                    .addComponent(Add5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l8)
                    .addComponent(Add6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_save)
                    .addComponent(Add_cnl))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout FlightDialogLayout = new javax.swing.GroupLayout(FlightDialog.getContentPane());
        FlightDialog.getContentPane().setLayout(FlightDialogLayout);
        FlightDialogLayout.setHorizontalGroup(
            FlightDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FlightDialogLayout.setVerticalGroup(
            FlightDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 18, 32));

        sidebar.setBackground(new java.awt.Color(15, 23, 36));
        sidebar.setFocusable(false);
        sidebar.setPreferredSize(new java.awt.Dimension(150, 0));
        sidebar.setVerifyInputWhenFocusTarget(false);
        sidebar.setLayout(new java.awt.GridLayout(6, 1, 0, 1));

        DashboardButton.setBackground(new java.awt.Color(7, 16, 26));
        DashboardButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        DashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        DashboardButton.setText("DASHBOARD");
        DashboardButton.setBorder(null);
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });
        sidebar.add(DashboardButton);

        FlightsButton.setBackground(new java.awt.Color(7, 16, 26));
        FlightsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        FlightsButton.setForeground(new java.awt.Color(255, 255, 255));
        FlightsButton.setText("MANAGE FLIGHTS");
        FlightsButton.setBorder(null);
        FlightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightsButtonActionPerformed(evt);
            }
        });
        sidebar.add(FlightsButton);

        BookingsButton.setBackground(new java.awt.Color(7, 16, 26));
        BookingsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        BookingsButton.setForeground(new java.awt.Color(255, 255, 255));
        BookingsButton.setText("MANAGE BOOKING");
        BookingsButton.setBorder(null);
        BookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingsButtonActionPerformed(evt);
            }
        });
        sidebar.add(BookingsButton);

        UsersButton.setBackground(new java.awt.Color(7, 16, 26));
        UsersButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        UsersButton.setForeground(new java.awt.Color(255, 255, 255));
        UsersButton.setText("USERS");
        UsersButton.setBorder(null);
        UsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButtonActionPerformed(evt);
            }
        });
        sidebar.add(UsersButton);

        ReportsButton.setBackground(new java.awt.Color(7, 16, 26));
        ReportsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        ReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportsButton.setText("REPORTS");
        ReportsButton.setBorder(null);
        ReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsButtonActionPerformed(evt);
            }
        });
        sidebar.add(ReportsButton);

        SettingsButton.setBackground(new java.awt.Color(7, 16, 26));
        SettingsButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        SettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        SettingsButton.setText("SETTINGS");
        SettingsButton.setBorder(null);
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });
        sidebar.add(SettingsButton);

        topbar.setBackground(new java.awt.Color(7, 16, 26));
        topbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        topbar.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AirNexa Admin Panel");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        topbar.add(jLabel1, java.awt.BorderLayout.CENTER);

        topbarleft.setOpaque(false);
        topbarleft.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setBackground(new java.awt.Color(11, 21, 32));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setText("🔔");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        topbarleft.add(jButton1);

        logout_btn.setBackground(new java.awt.Color(200, 21, 32));
        logout_btn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        logout_btn.setText("LOGOUT");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        topbarleft.add(logout_btn);

        topbar.add(topbarleft, java.awt.BorderLayout.LINE_END);

        menu.setBackground(new java.awt.Color(11, 18, 32));

        Burger.setBackground(new java.awt.Color(20, 21, 32));
        Burger.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        Burger.setText("=");
        Burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerActionPerformed(evt);
            }
        });
        menu.add(Burger);

        topbar.add(menu, java.awt.BorderLayout.LINE_START);

        MainPanel.setBackground(new java.awt.Color(11, 18, 32));
        MainPanel.setLayout(new java.awt.CardLayout());

        FlightsPanel.setBackground(new java.awt.Color(11, 18, 32));
        FlightsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FlightsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FlightsPanel.setLayout(new java.awt.BorderLayout());

        flighttable.setBackground(new java.awt.Color(11, 18, 32));
        flighttable.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        flighttable.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(11, 18, 32));

        flightTable.setAutoCreateRowSorter(true);
        flightTable.setBackground(new java.awt.Color(7, 16, 24));
        flightTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        flightTable.setForeground(new java.awt.Color(255, 255, 255));
        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight No.", "Airline", "Source", "Departure_Time", "Destination", "Arrival_Time", "Seat_Availability", "Ticket_Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flightTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flightTable.setFillsViewportHeight(true);
        flightTable.setGridColor(new java.awt.Color(30, 41, 55));
        flightTable.setPreferredSize(new java.awt.Dimension(300, 150));
        flightTable.setSelectionBackground(new java.awt.Color(6, 182, 212));
        flightTable.setShowVerticalLines(true);
        flightTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(flightTable);

        flighttable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        FlightsPanel.add(flighttable, java.awt.BorderLayout.CENTER);

        top.setBackground(new java.awt.Color(11, 18, 32));
        top.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        top.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(200, 200, 200));
        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Flights ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        top.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(11, 21, 32));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        addflight.setBackground(new java.awt.Color(14, 165, 164));
        addflight.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        addflight.setForeground(new java.awt.Color(255, 255, 255));
        addflight.setText("ADD");
        addflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addflightActionPerformed(evt);
            }
        });
        jPanel1.add(addflight);

        editflight.setBackground(new java.awt.Color(31, 41, 55));
        editflight.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        editflight.setForeground(new java.awt.Color(255, 255, 255));
        editflight.setText("EDIT");
        editflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editflightActionPerformed(evt);
            }
        });
        jPanel1.add(editflight);

        deleteflight.setBackground(new java.awt.Color(239, 68, 68));
        deleteflight.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        deleteflight.setForeground(new java.awt.Color(255, 255, 255));
        deleteflight.setText("DELETE");
        deleteflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteflightActionPerformed(evt);
            }
        });
        jPanel1.add(deleteflight);

        top.add(jPanel1, java.awt.BorderLayout.LINE_END);

        FlightsPanel.add(top, java.awt.BorderLayout.PAGE_START);

        MainPanel.add(FlightsPanel, "FlightBox");

        BookingsPanel.setBackground(new java.awt.Color(11, 18, 32));
        BookingsPanel.setLayout(new java.awt.BorderLayout());

        book_top.setBackground(new java.awt.Color(11, 18, 32));
        book_top.setForeground(new java.awt.Color(255, 255, 255));
        book_top.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(11, 18, 32));
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("🧾 BOOKINGS");
        book_top.add(jLabel2, java.awt.BorderLayout.CENTER);

        BookingsPanel.add(book_top, java.awt.BorderLayout.PAGE_START);

        bookingtable.setBackground(new java.awt.Color(11, 18, 32));
        bookingtable.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(11, 18, 32));

        bookingTable.setAutoCreateRowSorter(true);
        bookingTable.setBackground(new java.awt.Color(7, 16, 24));
        bookingTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        bookingTable.setForeground(new java.awt.Color(255, 255, 255));
        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "User ID", "Flight ID", "Date time", "Ticket Price", "No. Of Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookingTable.setToolTipText("");
        bookingTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookingTable.setFillsViewportHeight(true);
        bookingTable.setGridColor(new java.awt.Color(30, 41, 55));
        bookingTable.setPreferredSize(new java.awt.Dimension(300, 150));
        bookingTable.setSelectionBackground(new java.awt.Color(6, 182, 212));
        bookingTable.setShowVerticalLines(true);
        bookingTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(bookingTable);

        bookingtable.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        BookingsPanel.add(bookingtable, java.awt.BorderLayout.CENTER);

        MainPanel.add(BookingsPanel, "BookingBox");

        UsersPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout UsersPanelLayout = new javax.swing.GroupLayout(UsersPanel);
        UsersPanel.setLayout(UsersPanelLayout);
        UsersPanelLayout.setHorizontalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1574, Short.MAX_VALUE)
        );
        UsersPanelLayout.setVerticalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );

        MainPanel.add(UsersPanel, "UsersBox");

        ReportsPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout ReportsPanelLayout = new javax.swing.GroupLayout(ReportsPanel);
        ReportsPanel.setLayout(ReportsPanelLayout);
        ReportsPanelLayout.setHorizontalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1574, Short.MAX_VALUE)
        );
        ReportsPanelLayout.setVerticalGroup(
            ReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );

        MainPanel.add(ReportsPanel, "ReportsBox");

        SettingsPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1574, Short.MAX_VALUE)
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );

        MainPanel.add(SettingsPanel, "SettingsBox");

        DashBoardPanel.setBackground(new java.awt.Color(11, 18, 32));

        javax.swing.GroupLayout DashBoardPanelLayout = new javax.swing.GroupLayout(DashBoardPanel);
        DashBoardPanel.setLayout(DashBoardPanelLayout);
        DashBoardPanelLayout.setHorizontalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1574, Short.MAX_VALUE)
        );
        DashBoardPanelLayout.setVerticalGroup(
            DashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );

        MainPanel.add(DashBoardPanel, "DashBoardBox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightsButtonActionPerformed

        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "FlightBox");
        System.out.println("Flights clicked");

        try {
            con = airnexa.DatabaseConnection.getConnection();
            String sql = "SELECT * FROM flight";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel ob = (DefaultTableModel) flightTable.getModel();
            ob.setRowCount(0);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("flight_id"),
                    rs.getString("flight_no"),
                    rs.getString("airline"),
                    rs.getString("depart_from"),
                    rs.getString("departure_time"),
                    rs.getString("arrive_at"),
                    rs.getString("arrival_time"),
                    rs.getInt("seat_availability"),
                    rs.getFloat("ticket_price")
                };
                ob.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading flights: " + e.getMessage());
        }

    }//GEN-LAST:event_FlightsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?", "Confirm Logout",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            //Login ob = new Login(/*null,null*/);
//        this.hide();
//        ob.show();
        }
    }//GEN-LAST:event_logout_btnActionPerformed

    private void BookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "BookingBox");
    }//GEN-LAST:event_BookingsButtonActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "ReportsBox");
    }//GEN-LAST:event_ReportsButtonActionPerformed

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "DashBoardBox");
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "SettingsBox");
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void UsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButtonActionPerformed
        CardLayout cl = (CardLayout) (MainPanel.getLayout());
        cl.show(MainPanel, "UsersBox");
    }//GEN-LAST:event_UsersButtonActionPerformed

    private void BurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerActionPerformed
        toggleSidebar();
    }//GEN-LAST:event_BurgerActionPerformed

    private void deleteflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteflightActionPerformed
        // TODO add your handling code here:
        int selectedRow = flightTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a flight to delete");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this flight?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            deleteFlight(selectedRow);
        }
    }//GEN-LAST:event_deleteflightActionPerformed

    private void addflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addflightActionPerformed
        // TODO add your handling code here:
        isEditMode = false;
        editingFlightId = -1;
        openFlightDialog(false, null);
    }//GEN-LAST:event_addflightActionPerformed

    private void editflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editflightActionPerformed
        // TODO add your handling code here:
        int selectedRow = flightTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a flight to edit");
            return;
        }
        isEditMode = true;
        editingFlightId = (Integer) flightTable.getValueAt(selectedRow, 0);
        openFlightDialog(true, selectedRow);
    }//GEN-LAST:event_editflightActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Add_cnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_cnlActionPerformed
        // TODO add your handling code here:
        FlightDialog.setVisible(false);
    }//GEN-LAST:event_Add_cnlActionPerformed

    private void Add_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_saveActionPerformed
        String flightNo = Add1.getText().trim();
        String airline = Add2.getText().trim();
        String source = Add3.getText().trim();
        String destination = Add4.getText().trim();
        String seats = Add5.getText().trim();
        String price = Add6.getText().trim();

        if (flightNo.isEmpty() || airline.isEmpty() || source.isEmpty()
                || destination.isEmpty() || seats.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

        try {
            int seatCount = Integer.parseInt(seats);
            double priceValue = Double.parseDouble(price);

            java.util.Date depDate = (java.util.Date) depert.getValue();
            java.util.Date arrDate = (java.util.Date) jSpinner2.getValue();

            if (isEditMode) {
                updateFlightInDB(editingFlightId, flightNo, airline, source, destination,
                        new Timestamp(depDate.getTime()),
                        new Timestamp(arrDate.getTime()),
                        seatCount, priceValue);
            } else {
                addFlightToDB(flightNo, airline, source, destination,
                        new Timestamp(depDate.getTime()),
                        new Timestamp(arrDate.getTime()),
                        seatCount, priceValue);
            }

            FlightDialog.setVisible(false);
            loadFlightData(); // Refresh table

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number format for seats or price");
        }
    }//GEN-LAST:event_Add_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashBoard().setVisible(true));
    }

    private void loadBookingsData() {
        try {
            con = airnexa.DatabaseConnection.getConnection();
            String sql = "SELECT * FROM booking";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel ob = (DefaultTableModel) bookingTable.getModel();
            ob.setRowCount(0);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("booking_id"),
                    rs.getInt("user_id"),
                    rs.getInt("flight_id"),
                    rs.getString("date_time"),
                    rs.getFloat("ticket_price"),
                    rs.getInt("number_of_seats")
                };
                ob.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading flights: " + e.getMessage());
        } finally {
            // Close resources
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
            }
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
            }
        }
    }

    private void loadFlightData() {
        try {
            con = airnexa.DatabaseConnection.getConnection();
            String sql = "SELECT * FROM flight";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            DefaultTableModel ob = (DefaultTableModel) flightTable.getModel();
            ob.setRowCount(0);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("flight_id"),
                    rs.getString("flight_no"),
                    rs.getString("airline"),
                    rs.getString("depart_from"),
                    rs.getString("departure_time"),
                    rs.getString("arrive_at"),
                    rs.getString("arrival_time"),
                    rs.getInt("seat_availability"),
                    rs.getFloat("ticket_price")
                };
                ob.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading flights: " + e.getMessage());
        } finally {
            // Close resources
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
            }
            try {
                if (stmt != null) {
                    stmt.close();
                }
            } catch (Exception e) {
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
            }
        }
    }

    private void addFlightToDB(String flightNo, String airline, String source, String destination,
            Timestamp depTime, Timestamp arrTime, int seats, double price) {
        try {
            con = airnexa.DatabaseConnection.getConnection();
            String sql = "INSERT INTO flight (flight_no, airline, depart_from, departure_time, arrive_at, arrival_time, seat_availability, ticket_price) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, flightNo);
            pst.setString(2, airline);
            pst.setString(3, source);
            pst.setTimestamp(4, depTime);
            pst.setString(5, destination);
            pst.setTimestamp(6, arrTime);
            pst.setInt(7, seats);
            pst.setDouble(8, price);

            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Flight added successfully!");
            }

            pst.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding flight: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void updateFlightInDB(int flightId, String flightNo, String airline, String source,
            String destination, Timestamp depTime, Timestamp arrTime, int seats, double price) {
        try {
            con = airnexa.DatabaseConnection.getConnection();
            String sql = "UPDATE flight SET flight_no=?, airline=?, depart_from=?, departure_time=?, "
                    + "arrive_at=?, arrival_time=?, seat_availability=?, ticket_price=? WHERE flight_id=?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, flightNo);
            pst.setString(2, airline);
            pst.setString(3, source);
            pst.setTimestamp(4, depTime);
            pst.setString(5, destination);
            pst.setTimestamp(6, arrTime);
            pst.setInt(7, seats);
            pst.setDouble(8, price);
            pst.setInt(9, flightId);

            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Flight updated successfully!");
            }

            pst.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating flight: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void deleteFlight(int selectedRow) {
        try {
            // Get the flight ID from selected row
            int flightId = (Integer) flightTable.getValueAt(selectedRow, 0);

            con = airnexa.DatabaseConnection.getConnection();
            String sql = "DELETE FROM flight WHERE flight_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, flightId);

            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Flight deleted successfully!");
                loadFlightData(); // Refresh table
            } else {
                JOptionPane.showMessageDialog(this, "No flight found with that ID");
            }

            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting flight: " + e.getMessage());
        }
    }

    private void toggleSidebar() {
        sidebarVisible = !sidebarVisible;
        if (sidebarTimer != null && sidebarTimer.isRunning()) {
            sidebarTimer.stop();
        }

        final int targetWidth = sidebarVisible ? 220 : 0;
        final int step = 5;
        final int delay = 5;

        sidebarTimer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int currentWidth = sidebar.getWidth();

                if (sidebarVisible && currentWidth < targetWidth) {
                    sidebar.setPreferredSize(new Dimension(currentWidth + step, sidebar.getHeight()));
                } else if (!sidebarVisible && currentWidth > targetWidth) {
                    sidebar.setPreferredSize(new Dimension(currentWidth - step, sidebar.getHeight()));
                } else {
                    ((Timer) e.getSource()).stop();
                    sidebar.setPreferredSize(new Dimension(targetWidth, sidebar.getHeight()));
                    return;
                }

                revalidate();
                repaint();
            }
        });

        sidebarTimer.start();
    }

    private boolean validateFlightForm() {
        if (Add1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Flight number is required");
            Add1.requestFocus();
            return false;
        }

        if (Add2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Airline is required");
            Add2.requestFocus();
            return false;
        }

        // Validate other fields similarly...
        try {
            Integer.parseInt(Add5.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Seats must be a number");
            Add5.requestFocus();
            return false;
        }

        try {
            Double.parseDouble(Add6.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a number");
            Add6.requestFocus();
            return false;
        }

        return true;
    }

    private void openFlightDialog(boolean isEdit, Integer selectedRow) {
        Add1.setText("");
        Add2.setText("");
        Add3.setText("");
        Add4.setText("");
        Add5.setText("");
        Add6.setText("");

        depert.setValue(new java.util.Date());
        jSpinner2.setValue(new java.util.Date());

        if (isEdit && selectedRow != null) {
            Add1.setText(flightTable.getValueAt(selectedRow, 1).toString()); // Flight No
            Add2.setText(flightTable.getValueAt(selectedRow, 2).toString()); // Airline
            Add3.setText(flightTable.getValueAt(selectedRow, 3).toString()); // Source
            Add4.setText(flightTable.getValueAt(selectedRow, 5).toString()); // Destination
            Add5.setText(flightTable.getValueAt(selectedRow, 7).toString()); // Seats
            Add6.setText(flightTable.getValueAt(selectedRow, 8).toString()); // Price

            FlightDialog.setTitle("Edit Flight");
        } else {

            FlightDialog.setTitle("Add New Flight");
        }

        FlightDialog.pack();
        FlightDialog.setLocationRelativeTo(this);
        FlightDialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add1;
    private javax.swing.JTextField Add2;
    private javax.swing.JTextField Add3;
    private javax.swing.JTextField Add4;
    private javax.swing.JTextField Add5;
    private javax.swing.JTextField Add6;
    private javax.swing.JButton Add_cnl;
    private javax.swing.JButton Add_save;
    private javax.swing.JToggleButton BookingsButton;
    private javax.swing.JPanel BookingsPanel;
    private javax.swing.JButton Burger;
    private javax.swing.JPanel DashBoardPanel;
    private javax.swing.JToggleButton DashboardButton;
    private javax.swing.JDialog FlightDialog;
    private javax.swing.JToggleButton FlightsButton;
    private javax.swing.JPanel FlightsPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JToggleButton ReportsButton;
    private javax.swing.JPanel ReportsPanel;
    private javax.swing.JToggleButton SettingsButton;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JToggleButton UsersButton;
    private javax.swing.JPanel UsersPanel;
    private javax.swing.JButton addflight;
    private javax.swing.JPanel book_top;
    private javax.swing.JTable bookingTable;
    private javax.swing.JPanel bookingtable;
    private javax.swing.JButton deleteflight;
    private javax.swing.JSpinner depert;
    private javax.swing.JButton editflight;
    private javax.swing.JTable flightTable;
    private javax.swing.JPanel flighttable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JButton logout_btn;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel top;
    private javax.swing.JPanel topbar;
    private javax.swing.JPanel topbarleft;
    // End of variables declaration//GEN-END:variables
}
